name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - '**'        # run on ALL branches (main + feature branches)
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: python -m unittest discover -s . -p "test_*.py"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t cicd_pipeline_products .

    - name: Run Container
      run: docker run -d -p 5000:5000 --name cicd_pipeline_products cicd_pipeline_products

    - name: Wait for app to start
      run: sleep 10

    - name: Health Check
      run: |
        curl --fail http://localhost:5000 || (docker logs cicd_pipeline_products && exit 1)

    - name: Stop Container
      if: always()
      run: docker stop cicd_pipeline_products

     # Log in to Docker Hub
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Push Docker Image to Docker Hub
    - name: Push Docker Image
      if: github.ref == 'refs/heads/main'
      run: |
        # Set dynamic version tag using GitHub run number
        VERSION_TAG=v${{ github.run_number }}

        # Tag both versioned and latest images
        # docker tag cicd_pipeline_products ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_pipeline_products:${VERSION_TAG}
        docker tag cicd_pipeline_products ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_pipeline_products:latest

        # Push both
        # docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_pipeline_products:${VERSION_TAG}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_pipeline_products:latest